"""Add thumbnail_path to events table

Revision ID: 72c78fa47718
Revises: 'None'
Create Date: 2025-11-14 18:53:41.657979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c78fa47718'
down_revision: Union[str, None] = 'None'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'thumbnail_path')
    # ### end Alembic commands ###